[32m2022-01-12 21:22:41[0m - dagster - [34mDEBUG[0m - dagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - 106892 - call_local_data - LOGS_CAPTURED - Started capturing logs for solid: call_local_data.
[32m2022-01-12 21:22:41[0m - dagster - [34mDEBUG[0m - dagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - 106892 - call_local_data - STEP_START - Started execution of step "call_local_data".
[32m2022-01-12 21:22:41[0m - dagster - [34mDEBUG[0m - dagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - call_local_data - Loading file from: /home/heiko/Repos/dagster_azurite/tmp5cyupl2r/storage/e526290f-9c16-46b7-875c-50d37051ef51/local_name_string/result
[32m2022-01-12 21:22:41[0m - dagster - [34mDEBUG[0m - dagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - 106892 - call_local_data - LOADED_INPUT - Loaded input "path" using input manager "io_manager", from output "result" of step "local_name_string"
[32m2022-01-12 21:22:41[0m - dagster - [34mDEBUG[0m - dagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - 106892 - call_local_data - STEP_INPUT - Got input "path" of type "Any". (Type check passed).
[32m2022-01-12 21:22:41[0m - dagster - [34mINFO[0m - dagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - call_local_data - path: ./sampledata_folder/sampledata.csv
[32m2022-01-12 21:22:41[0m - dagster - [34mERROR[0m - [31mdagster_pipeline_sensor - e526290f-9c16-46b7-875c-50d37051ef51 - 106892 - call_local_data - STEP_FAILURE - Execution of step "call_local_data" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "call_local_data"::

FileNotFoundError: [Errno 2] No such file or directory: './sampledata_folder/sampledata.csv'

Stack Trace:
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 44, in solid_execution_error_boundary
    yield
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/dagster/utils/__init__.py", line 383, in iterate_with_context
    next_output = next(iterator)
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/home/heiko/Repos/dagster_azurite/data_pipeline/ops.py", line 52, in call_local_data
    data = pd.read_csv(datapath, sep = ",")
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/heiko/Repos/dagster_azurite/.venv/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
[0m
